name: FriCAS CI on Linux

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install sbcl libgmp-dev libxpm-dev
    - name: configure
      run: ./configure --with-lisp="sbcl --dynamic-space-size 2048" --with-gmp --with-x || cat config.log
    - name: make
      run: make -j2 --output-sync
    - name: make check
      run: make check -j2 --output-sync
    - name: Create artifact archives
      run: |
        test "$GITHUB_REF_TYPE" != "tag" && rm -r target/*/src
        tar -cjf FriCAS-linux-x86_64-${{ github.sha }}.tar.bz2 target/
    - name: Upload Linux binary
      uses: actions/upload-artifact@v4
      with:
        name: FriCAS-linux-x86_64-binary
        path: FriCAS-linux-x86_64-${{ github.sha }}.tar.bz2
