name: FriCAS CI on macOS (with Julia support - SBCL based)

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest
    timeout-minutes: 30
    env:
      SBCL_VER: 2.2.9

    steps:
    - uses: actions/checkout@v4
    - name: download and install SBCL
      run: |
        wget https://downloads.sourceforge.net/project/sbcl/sbcl/${SBCL_VER}/sbcl-${SBCL_VER}-x86-64-darwin-binary.tar.bz2
        tar xvf sbcl-${SBCL_VER}-x86-64-darwin-binary.tar.bz2
        cd sbcl-${SBCL_VER}-x86-64-darwin && ./install.sh
    - name: download Julia
      run: wget -c https://julialang-s3.julialang.org/bin/mac/x64/1.10/julia-1.10.0-mac64.dmg
    - name: mount Julia
      run: hdiutil mount julia-1.10.0-mac64.dmg
    - name: install Julia
      run: |
        sudo cp -R /Volumes/julia-1.10.0/julia-1.10.app /Applications
        sudo ln -sf /Applications/Julia-1.10.app/Contents/Resources/julia/bin/julia /usr/local/bin/julia
        sudo ln -sf /Applications/Julia-1.10.app/Contents/Resources/julia/lib/libjulia.dylib /usr/local/lib/libjulia.dylib
    - name: adjust lib search path
      run: export DYLD_FALLBACK_LIBRARY_PATH=/Applications/Julia-1.10.app/Contents/Resources/julia/lib:$DYLD_FALLBACK_LIBRARY_PATH  && sudo update_dyld_shared_cache
    - name: configure
      run: |
        mkdir ../build && cd ../build
        ../fricas/configure --with-lisp="sbcl --dynamic-space-size 2048" --enable-gmp --enable-julia || cat config.log
    - name: make
      run: cd ../build && make -j3
    - name: make check
      run: cd ../build && make check -j3
    - name: Create artifact archives
      run: |
        cd ../build
        rm -r target/*/src
        make dist-macos
        cp -v `brew list gmp | grep libgmp.10.dylib` FriCAS.app/Contents/Resources/usr/local/lib/fricas/target/*/lib/
        make dist-macos-dmg
        mv FriCAS.dmg ../fricas/FriCAS-macOS-x86_64-${{ github.sha }}.dmg
    - name: Upload macOS binary
      uses: actions/upload-artifact@v3
      with:
        name: FriCAS-macOS-x86_64-binary
        path: FriCAS-macOS-x86_64-${{ github.sha }}.dmg
