name: FriCAS CI on Windows (with Julia support - SBCL based)

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2019
    timeout-minutes: 30
    env:
      SBCL_VER: 2.3.2
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        install: make mingw-w64-x86_64-gcc mingw-w64-x86_64-gmp gmp-devel zip unzip
    - name: download and install SBCL
      run: |
        wget https://downloads.sourceforge.net/project/sbcl/sbcl/${SBCL_VER}/sbcl-${SBCL_VER}-x86-64-windows-binary.msi
        msiexec -i sbcl-${SBCL_VER}-x86-64-windows-binary.msi -passive
    - name: download and install Julia
      run: |
        wget https://julialang-s3.julialang.org/bin/winnt/x64/1.10/julia-1.10.0-win64.zip
        unzip julia-1.10.0-win64.zip
        cp -rf julia-1.10.0/* /usr/local/
    - uses: actions/checkout@v4
    - name: configure and make
      run: |
        export SBCL_HOME="/c/Program Files/Steel Bank Common Lisp/"
        export PATH="$SBCL_HOME":$PATH
        mkdir ../build && cd ../build
        ../fricas/configure --with-lisp="sbcl --dynamic-space-size 2048" --enable-gmp --enable-julia || cat config.log
        make -j2 --output-sync
    - name: make check
      run: cd ../build && make check -j2 --output-sync
    - name: Create artifact archives
      run: |
        test "$GITHUB_REF_TYPE" != "tag" && rm -r ../build/target/*/src
        rm ../build/target/x86_64-w64-mingw32/bin/fricas
        mv ../build/target/x86_64-w64-mingw32 FriCAS-windows-x86_64
        cp /mingw64/bin/libgmp-10.dll FriCAS-windows-x86_64/lib/
        zip -r FriCAS-windows-x86_64-${{ github.sha }}.zip FriCAS-windows-x86_64
    - name: Upload Windows binary
      uses: actions/upload-artifact@v4
      with:
        name: FriCAS-windows-x86_64-binary
        path: FriCAS-windows-x86_64-${{ github.sha }}.zip
